version: '3.7'

services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "8080:80"
    networks:
      - webnet

networks:
  webnet:
